name: Generate CV.html from CV.md

on:
  push
  
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --self-contained
            --from markdown
            --to html
            -o cv.html
            cv.md
