name: Generate CV.html from CV.md

on:
  push
  
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Prepare files
        run: |
          mkdir output

      - name: Build HTML
        uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone 
            --from markdown 
            --to pdf 
            -o output/cv.pdf 
            cv.md

      - name: Archive builded page
        uses: actions/upload-artifact@v3
        with:
          name: cv-pdf
          path: output/cv.pdf
